/// -- Job defines. --
#define JOB_DISPLAY_ORDER_ASSET_PROTECTION 3.1
#define JOB_DISPLAY_ORDER_BRIDGE_OFFICER 3.2
#define JOB_DISPLAY_ORDER_ORDNANCE_TECH 29.1
#define JOB_DISPLAY_ORDER_XENOBIOLOGIST 29.2

#define JOB_SYNDICATE (1<<0)
