/// -- Job defines. --
#define JOB_DISPLAY_ORDER_BRIDGE_OFFICER 3
#define JOB_DISPLAY_ORDER_ASSET_PROTECTION 4
#define JOB_DISPLAY_ORDER_TOXICOLOGIST 31
#define JOB_DISPLAY_ORDER_XENOBIOLOGIST 32

#define JOB_SYNDICATE (1<<0)
